# Generated by Django 3.2 on 2022-03-11 21:04

from django.db import migrations, models
import passanger.models


class Migration(migrations.Migration):

    dependencies = [
        ('passanger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='recet_number',
            field=models.CharField(default=passanger.models.f, max_length=18, unique=True),
        ),
    ]
