# Generated by Django 3.2 on 2022-03-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_trip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
    ]
